# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UrlShortener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual', models.URLField()),
                ('short', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.DeleteModel(
            name='UrlField',
        ),
    ]
